services:
  database:
    container_name: ecommerce
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ecommerce
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: