# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters

[environments.local]
url = "jdbc:postgresql://172.18.0.1/ecommerce"
user = "paul"
schemas = ["ecommerce"]

[environments.azure]
url = "jdbc:postgresql://vacation-work-2024.postgres.database.azure.com:5432/postgres"
user = "formationadminuser"
schemas = ["ecommerce"]

[flyway]
locations = ["filesystem:migrations"]
cleanDisabled = false
validateMigrationNaming=true
reportEnabled = true
table = "FlywayHistory"
baselineVersion = "2021.11.000"
baselineDescription = "Baseline before converting to flyway migrations"