[environments.local]
url = "jdbc:postgresql://localhost:5432/paul"
user = "paul"
schemas = ["ecommerce"]

[flyway]
locations = ["filesystem:migrations"]
cleanDisabled = false
validateMigrationNaming=true
reportEnabled = true
table = "FlywayHistory"
baselineVersion = "2021.11.000"
baselineDescription = "Baseline before converting to flyway migrations"