import type { INavLink } from "./types";

export const categories: INavLink[] = [
    { text: "Men", href: "#" },
    { text: "Women", href: "#" },
    { text: "Children", href: "#" },
    { text: "Electronics", href: "#" },
    { text: "Home & Kitchen", href: "#" },
    { text: "Beauty & Personal Care", href: "#" },
    { text: "Health & Wellness", href: "#" },
    { text: "Sports & Outdoors", href: "#" },
    { text: "Books & Stationery", href: "#" },
    { text: "Groceries", href: "#" },
    { text: "Toys & Games", href: "#" },
    { text: "Baby Products", href: "#" },
    { text: "Jewelry", href: "#" },
    { text: "Shoes & Accessories", href: "#" },
    { text: "Automotive", href: "#" },
    { text: "Tools & DIY", href: "#" },
    { text: "Pet Supplies", href: "#" },
    { text: "Furniture", href: "#" },
    { text: "Office Supplies", href: "#" },
    { text: "Arts & Crafts", href: "#" },
    { text: "Gaming", href: "#" },
    { text: "Mobile Phones & Tablets", href: "#" },
    { text: "Watches", href: "#" },
    { text: "Bags & Luggage", href: "#" },
    { text: "Garden & Outdoor", href: "#" },
    { text: "Musical Instruments", href: "#" },
    { text: "Luxury", href: "#" },
    { text: "Deals & Promotions", href: "#" },
    { text: "Digital Goods", href: "#" },
    { text: "Subscriptions & Services", href: "#" }
];
