ALTER TABLE Department
    ADD COLUMN image_url VARCHAR(255);

ALTER TABLE Vendor
    ADD COLUMN last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Vendor
    ADD COLUMN ig_username VARCHAR(30) UNIQUE;