-- Create the sizes table
CREATE TABLE Sizes (
    size_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category VARCHAR(100) NOT NULL,
    size_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Sizes (category, size_name) VALUES
-- Clothing Sizes - General
('Clothing - General', 'XXS'),
('Clothing - General', 'XS'),
('Clothing - General', 'S'),
('Clothing - General', 'M'),
('Clothing - General', 'L'),
('Clothing - General', 'XL'),
('Clothing - General', 'XXL'),
('Clothing - General', 'XXXL'),
('Clothing - General', '4XL'),
('Clothing - General', '5XL'),
('Clothing - General', '6XL'),
('Clothing - General', '7XL'),
('Clothing - General', '8XL'),

-- Numeric Clothing Sizes (US)
('Clothing - US Numeric', '0'),
('Clothing - US Numeric', '2'),
('Clothing - US Numeric', '4'),
('Clothing - US Numeric', '6'),
('Clothing - US Numeric', '8'),
('Clothing - US Numeric', '10'),
('Clothing - US Numeric', '12'),
('Clothing - US Numeric', '14'),
('Clothing - US Numeric', '16'),
('Clothing - US Numeric', '18'),
('Clothing - US Numeric', '20'),
('Clothing - US Numeric', '22'),
('Clothing - US Numeric', '24'),
('Clothing - US Numeric', '26'),
('Clothing - US Numeric', '28'),
('Clothing - US Numeric', '30'),
('Clothing - US Numeric', '32'),

-- European Clothing Sizes
('Clothing - European', 'EU32'),
('Clothing - European', 'EU34'),
('Clothing - European', 'EU36'),
('Clothing - European', 'EU38'),
('Clothing - European', 'EU40'),
('Clothing - European', 'EU42'),
('Clothing - European', 'EU44'),
('Clothing - European', 'EU46'),
('Clothing - European', 'EU48'),
('Clothing - European', 'EU50'),
('Clothing - European', 'EU52'),
('Clothing - European', 'EU54'),
('Clothing - European', 'EU56'),
('Clothing - European', 'EU58'),
('Clothing - European', 'EU60'),

-- UK Clothing Sizes
('Clothing - UK', 'UK4'),
('Clothing - UK', 'UK6'),
('Clothing - UK', 'UK8'),
('Clothing - UK', 'UK10'),
('Clothing - UK', 'UK12'),
('Clothing - UK', 'UK14'),
('Clothing - UK', 'UK16'),
('Clothing - UK', 'UK18'),
('Clothing - UK', 'UK20'),
('Clothing - UK', 'UK22'),
('Clothing - UK', 'UK24'),
('Clothing - UK', 'UK26'),
('Clothing - UK', 'UK28'),
('Clothing - UK', 'UK30'),

-- Shoe Sizes - US Men's
('Shoes - US Men''s', 'US_M_3'),
('Shoes - US Men''s', 'US_M_3.5'),
('Shoes - US Men''s', 'US_M_4'),
('Shoes - US Men''s', 'US_M_4.5'),
('Shoes - US Men''s', 'US_M_5'),
('Shoes - US Men''s', 'US_M_5.5'),
('Shoes - US Men''s', 'US_M_6'),
('Shoes - US Men''s', 'US_M_6.5'),
('Shoes - US Men''s', 'US_M_7'),
('Shoes - US Men''s', 'US_M_7.5'),
('Shoes - US Men''s', 'US_M_8'),
('Shoes - US Men''s', 'US_M_8.5'),
('Shoes - US Men''s', 'US_M_9'),
('Shoes - US Men''s', 'US_M_9.5'),
('Shoes - US Men''s', 'US_M_10'),
('Shoes - US Men''s', 'US_M_10.5'),
('Shoes - US Men''s', 'US_M_11'),
('Shoes - US Men''s', 'US_M_11.5'),
('Shoes - US Men''s', 'US_M_12'),
('Shoes - US Men''s', 'US_M_12.5'),
('Shoes - US Men''s', 'US_M_13'),
('Shoes - US Men''s', 'US_M_13.5'),
('Shoes - US Men''s', 'US_M_14'),
('Shoes - US Men''s', 'US_M_14.5'),
('Shoes - US Men''s', 'US_M_15'),
('Shoes - US Men''s', 'US_M_16'),
('Shoes - US Men''s', 'US_M_17'),
('Shoes - US Men''s', 'US_M_18'),

-- Shoe Sizes - US Women's
('Shoes - US Women''s', 'US_W_4'),
('Shoes - US Women''s', 'US_W_4.5'),
('Shoes - US Women''s', 'US_W_5'),
('Shoes - US Women''s', 'US_W_5.5'),
('Shoes - US Women''s', 'US_W_6'),
('Shoes - US Women''s', 'US_W_6.5'),
('Shoes - US Women''s', 'US_W_7'),
('Shoes - US Women''s', 'US_W_7.5'),
('Shoes - US Women''s', 'US_W_8'),
('Shoes - US Women''s', 'US_W_8.5'),
('Shoes - US Women''s', 'US_W_9'),
('Shoes - US Women''s', 'US_W_9.5'),
('Shoes - US Women''s', 'US_W_10'),
('Shoes - US Women''s', 'US_W_10.5'),
('Shoes - US Women''s', 'US_W_11'),
('Shoes - US Women''s', 'US_W_11.5'),
('Shoes - US Women''s', 'US_W_12'),
('Shoes - US Women''s', 'US_W_12.5'),
('Shoes - US Women''s', 'US_W_13'),
('Shoes - US Women''s', 'US_W_13.5'),
('Shoes - US Women''s', 'US_W_14'),
('Shoes - US Women''s', 'US_W_15'),

-- Shoe Sizes - European
('Shoes - European', 'EU35'),
('Shoes - European', 'EU35.5'),
('Shoes - European', 'EU36'),
('Shoes - European', 'EU36.5'),
('Shoes - European', 'EU37'),
('Shoes - European', 'EU37.5'),
('Shoes - European', 'EU38'),
('Shoes - European', 'EU38.5'),
('Shoes - European', 'EU39'),
('Shoes - European', 'EU39.5'),
('Shoes - European', 'EU40'),
('Shoes - European', 'EU40.5'),
('Shoes - European', 'EU41'),
('Shoes - European', 'EU41.5'),
('Shoes - European', 'EU42'),
('Shoes - European', 'EU42.5'),
('Shoes - European', 'EU43'),
('Shoes - European', 'EU43.5'),
('Shoes - European', 'EU44'),
('Shoes - European', 'EU44.5'),
('Shoes - European', 'EU45'),
('Shoes - European', 'EU45.5'),
('Shoes - European', 'EU46'),
('Shoes - European', 'EU46.5'),
('Shoes - European', 'EU47'),
('Shoes - European', 'EU47.5'),
('Shoes - European', 'EU48'),
('Shoes - European', 'EU48.5'),
('Shoes - European', 'EU49'),
('Shoes - European', 'EU49.5'),
('Shoes - European', 'EU50'),
('Shoes - European', 'EU51'),
('Shoes - European', 'EU52'),

-- Shoe Sizes - UK
('Shoes - UK', 'UK2'),
('Shoes - UK', 'UK2.5'),
('Shoes - UK', 'UK3'),
('Shoes - UK', 'UK3.5'),
('Shoes - UK', 'UK4'),
('Shoes - UK', 'UK4.5'),
('Shoes - UK', 'UK5'),
('Shoes - UK', 'UK5.5'),
('Shoes - UK', 'UK6'),
('Shoes - UK', 'UK6.5'),
('Shoes - UK', 'UK7'),
('Shoes - UK', 'UK7.5'),
('Shoes - UK', 'UK8'),
('Shoes - UK', 'UK8.5'),
('Shoes - UK', 'UK9'),
('Shoes - UK', 'UK9.5'),
('Shoes - UK', 'UK10'),
('Shoes - UK', 'UK10.5'),
('Shoes - UK', 'UK11'),
('Shoes - UK', 'UK11.5'),
('Shoes - UK', 'UK12'),
('Shoes - UK', 'UK12.5'),
('Shoes - UK', 'UK13'),
('Shoes - UK', 'UK13.5'),
('Shoes - UK', 'UK14'),
('Shoes - UK', 'UK15'),
('Shoes - UK', 'UK16'),

-- Children's Clothing - Age-based
('Children''s Clothing - Age', 'NEWBORN'),
('Children''s Clothing - Age', '0-3M'),
('Children''s Clothing - Age', '3-6M'),
('Children''s Clothing - Age', '6-9M'),
('Children''s Clothing - Age', '9-12M'),
('Children''s Clothing - Age', '12-18M'),
('Children''s Clothing - Age', '18-24M'),
('Children''s Clothing - Age', '2T'),
('Children''s Clothing - Age', '3T'),
('Children''s Clothing - Age', '4T'),
('Children''s Clothing - Age', '5T'),
('Children''s Clothing - Age', '6T'),

-- Children's Clothing - Size-based
('Children''s Clothing - Size', 'KIDS_XS'),
('Children''s Clothing - Size', 'KIDS_S'),
('Children''s Clothing - Size', 'KIDS_M'),
('Children''s Clothing - Size', 'KIDS_L'),
('Children''s Clothing - Size', 'KIDS_XL'),

-- Children's Shoe Sizes - US Toddler
('Children''s Shoes - Toddler', 'US_TODDLER_1'),
('Children''s Shoes - Toddler', 'US_TODDLER_1.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_2'),
('Children''s Shoes - Toddler', 'US_TODDLER_2.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_3'),
('Children''s Shoes - Toddler', 'US_TODDLER_3.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_4'),
('Children''s Shoes - Toddler', 'US_TODDLER_4.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_5'),
('Children''s Shoes - Toddler', 'US_TODDLER_5.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_6'),
('Children''s Shoes - Toddler', 'US_TODDLER_6.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_7'),
('Children''s Shoes - Toddler', 'US_TODDLER_7.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_8'),
('Children''s Shoes - Toddler', 'US_TODDLER_8.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_9'),
('Children''s Shoes - Toddler', 'US_TODDLER_9.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_10'),
('Children''s Shoes - Toddler', 'US_TODDLER_10.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_11'),
('Children''s Shoes - Toddler', 'US_TODDLER_11.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_12'),
('Children''s Shoes - Toddler', 'US_TODDLER_12.5'),
('Children''s Shoes - Toddler', 'US_TODDLER_13'),
('Children''s Shoes - Toddler', 'US_TODDLER_13.5'),

-- Children's Shoe Sizes - Little Kid
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_1'),
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_1.5'),
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_2'),
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_2.5'),
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_3'),
('Children''s Shoes - Little Kid', 'US_LITTLE_KID_3.5'),

-- Children's Shoe Sizes - Big Kid
('Children''s Shoes - Big Kid', 'US_BIG_KID_3.5'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_4'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_4.5'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_5'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_5.5'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_6'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_6.5'),
('Children''s Shoes - Big Kid', 'US_BIG_KID_7'),

-- Bra Sizes
('Bra Sizes', 'BRA_28A'),
('Bra Sizes', 'BRA_28B'),
('Bra Sizes', 'BRA_28C'),
('Bra Sizes', 'BRA_28D'),
('Bra Sizes', 'BRA_28DD'),
('Bra Sizes', 'BRA_28DDD'),
('Bra Sizes', 'BRA_30A'),
('Bra Sizes', 'BRA_30B'),
('Bra Sizes', 'BRA_30C'),
('Bra Sizes', 'BRA_30D'),
('Bra Sizes', 'BRA_30DD'),
('Bra Sizes', 'BRA_30DDD'),
('Bra Sizes', 'BRA_32A'),
('Bra Sizes', 'BRA_32B'),
('Bra Sizes', 'BRA_32C'),
('Bra Sizes', 'BRA_32D'),
('Bra Sizes', 'BRA_32DD'),
('Bra Sizes', 'BRA_32DDD'),
('Bra Sizes', 'BRA_34A'),
('Bra Sizes', 'BRA_34B'),
('Bra Sizes', 'BRA_34C'),
('Bra Sizes', 'BRA_34D'),
('Bra Sizes', 'BRA_34DD'),
('Bra Sizes', 'BRA_34DDD'),
('Bra Sizes', 'BRA_36A'),
('Bra Sizes', 'BRA_36B'),
('Bra Sizes', 'BRA_36C'),
('Bra Sizes', 'BRA_36D'),
('Bra Sizes', 'BRA_36DD'),
('Bra Sizes', 'BRA_36DDD'),
('Bra Sizes', 'BRA_38A'),
('Bra Sizes', 'BRA_38B'),
('Bra Sizes', 'BRA_38C'),
('Bra Sizes', 'BRA_38D'),
('Bra Sizes', 'BRA_38DD'),
('Bra Sizes', 'BRA_38DDD'),
('Bra Sizes', 'BRA_40A'),
('Bra Sizes', 'BRA_40B'),
('Bra Sizes', 'BRA_40C'),
('Bra Sizes', 'BRA_40D'),
('Bra Sizes', 'BRA_40DD'),
('Bra Sizes', 'BRA_40DDD'),
('Bra Sizes', 'BRA_42A'),
('Bra Sizes', 'BRA_42B'),
('Bra Sizes', 'BRA_42C'),
('Bra Sizes', 'BRA_42D'),
('Bra Sizes', 'BRA_42DD'),
('Bra Sizes', 'BRA_42DDD'),
('Bra Sizes', 'BRA_44A'),
('Bra Sizes', 'BRA_44B'),
('Bra Sizes', 'BRA_44C'),
('Bra Sizes', 'BRA_44D'),
('Bra Sizes', 'BRA_44DD'),
('Bra Sizes', 'BRA_44DDD'),

-- Pants/Jeans Sizes - Waist x Length
('Pants - Waist x Length', 'W26_L28'),
('Pants - Waist x Length', 'W26_L30'),
('Pants - Waist x Length', 'W26_L32'),
('Pants - Waist x Length', 'W26_L34'),
('Pants - Waist x Length', 'W28_L28'),
('Pants - Waist x Length', 'W28_L30'),
('Pants - Waist x Length', 'W28_L32'),
('Pants - Waist x Length', 'W28_L34'),
('Pants - Waist x Length', 'W28_L36'),
('Pants - Waist x Length', 'W30_L28'),
('Pants - Waist x Length', 'W30_L30'),
('Pants - Waist x Length', 'W30_L32'),
('Pants - Waist x Length', 'W30_L34'),
('Pants - Waist x Length', 'W30_L36'),
('Pants - Waist x Length', 'W32_L28'),
('Pants - Waist x Length', 'W32_L30'),
('Pants - Waist x Length', 'W32_L32'),
('Pants - Waist x Length', 'W32_L34'),
('Pants - Waist x Length', 'W32_L36'),
('Pants - Waist x Length', 'W34_L28'),
('Pants - Waist x Length', 'W34_L30'),
('Pants - Waist x Length', 'W34_L32'),
('Pants - Waist x Length', 'W34_L34'),
('Pants - Waist x Length', 'W34_L36'),
('Pants - Waist x Length', 'W36_L28'),
('Pants - Waist x Length', 'W36_L30'),
('Pants - Waist x Length', 'W36_L32'),
('Pants - Waist x Length', 'W36_L34'),
('Pants - Waist x Length', 'W36_L36'),
('Pants - Waist x Length', 'W38_L28'),
('Pants - Waist x Length', 'W38_L30'),
('Pants - Waist x Length', 'W38_L32'),
('Pants - Waist x Length', 'W38_L34'),
('Pants - Waist x Length', 'W38_L36'),
('Pants - Waist x Length', 'W40_L28'),
('Pants - Waist x Length', 'W40_L30'),
('Pants - Waist x Length', 'W40_L32'),
('Pants - Waist x Length', 'W40_L34'),
('Pants - Waist x Length', 'W40_L36'),
('Pants - Waist x Length', 'W42_L30'),
('Pants - Waist x Length', 'W42_L32'),
('Pants - Waist x Length', 'W42_L34'),
('Pants - Waist x Length', 'W42_L36'),
('Pants - Waist x Length', 'W44_L30'),
('Pants - Waist x Length', 'W44_L32'),
('Pants - Waist x Length', 'W44_L34'),
('Pants - Waist x Length', 'W44_L36'),
('Pants - Waist x Length', 'W46_L30'),
('Pants - Waist x Length', 'W46_L32'),
('Pants - Waist x Length', 'W46_L34'),
('Pants - Waist x Length', 'W46_L36'),
('Pants - Waist x Length', 'W48_L30'),
('Pants - Waist x Length', 'W48_L32'),
('Pants - Waist x Length', 'W48_L34'),
('Pants - Waist x Length', 'W48_L36'),
('Pants - Waist x Length', 'W50_L30'),
('Pants - Waist x Length', 'W50_L32'),
('Pants - Waist x Length', 'W50_L34'),
('Pants - Waist x Length', 'W50_L36'),

-- Hat Sizes
('Hat Sizes', 'HAT_XS_6.5'),
('Hat Sizes', 'HAT_S_6.75'),
('Hat Sizes', 'HAT_S_7'),
('Hat Sizes', 'HAT_M_7.125'),
('Hat Sizes', 'HAT_M_7.25'),
('Hat Sizes', 'HAT_L_7.375'),
('Hat Sizes', 'HAT_L_7.5'),
('Hat Sizes', 'HAT_XL_7.625'),
('Hat Sizes', 'HAT_XL_7.75'),
('Hat Sizes', 'HAT_XXL_7.875'),
('Hat Sizes', 'HAT_XXL_8'),

-- Ring Sizes - US
('Ring Sizes', 'RING_3'),
('Ring Sizes', 'RING_3.5'),
('Ring Sizes', 'RING_4'),
('Ring Sizes', 'RING_4.5'),
('Ring Sizes', 'RING_5'),
('Ring Sizes', 'RING_5.5'),
('Ring Sizes', 'RING_6'),
('Ring Sizes', 'RING_6.5'),
('Ring Sizes', 'RING_7'),
('Ring Sizes', 'RING_7.5'),
('Ring Sizes', 'RING_8'),
('Ring Sizes', 'RING_8.5'),
('Ring Sizes', 'RING_9'),
('Ring Sizes', 'RING_9.5'),
('Ring Sizes', 'RING_10'),
('Ring Sizes', 'RING_10.5'),
('Ring Sizes', 'RING_11'),
('Ring Sizes', 'RING_11.5'),
('Ring Sizes', 'RING_12'),
('Ring Sizes', 'RING_12.5'),
('Ring Sizes', 'RING_13'),
('Ring Sizes', 'RING_13.5'),
('Ring Sizes', 'RING_14'),
('Ring Sizes', 'RING_14.5'),
('Ring Sizes', 'RING_15'),

-- Electronics Screen Sizes (inches)
('Electronics - Screen Size', 'SCREEN_5.4'),
('Electronics - Screen Size', 'SCREEN_5.8'),
('Electronics - Screen Size', 'SCREEN_6.1'),
('Electronics - Screen Size', 'SCREEN_6.7'),
('Electronics - Screen Size', 'SCREEN_10.2'),
('Electronics - Screen Size', 'SCREEN_10.9'),
('Electronics - Screen Size', 'SCREEN_11'),
('Electronics - Screen Size', 'SCREEN_12.9'),
('Electronics - Screen Size', 'SCREEN_13'),
('Electronics - Screen Size', 'SCREEN_13.3'),
('Electronics - Screen Size', 'SCREEN_14'),
('Electronics - Screen Size', 'SCREEN_15'),
('Electronics - Screen Size', 'SCREEN_15.6'),
('Electronics - Screen Size', 'SCREEN_16'),
('Electronics - Screen Size', 'SCREEN_17'),
('Electronics - Screen Size', 'SCREEN_17.3'),
('Electronics - Screen Size', 'SCREEN_19'),
('Electronics - Screen Size', 'SCREEN_21.5'),
('Electronics - Screen Size', 'SCREEN_22'),
('Electronics - Screen Size', 'SCREEN_24'),
('Electronics - Screen Size', 'SCREEN_25'),
('Electronics - Screen Size', 'SCREEN_27'),
('Electronics - Screen Size', 'SCREEN_28'),
('Electronics - Screen Size', 'SCREEN_29'),
('Electronics - Screen Size', 'SCREEN_30'),
('Electronics - Screen Size', 'SCREEN_32'),
('Electronics - Screen Size', 'SCREEN_34'),
('Electronics - Screen Size', 'SCREEN_35'),
('Electronics - Screen Size', 'SCREEN_38'),
('Electronics - Screen Size', 'SCREEN_40'),
('Electronics - Screen Size', 'SCREEN_42'),
('Electronics - Screen Size', 'SCREEN_43'),
('Electronics - Screen Size', 'SCREEN_48'),
('Electronics - Screen Size', 'SCREEN_49'),
('Electronics - Screen Size', 'SCREEN_50'),
('Electronics - Screen Size', 'SCREEN_55'),
('Electronics - Screen Size', 'SCREEN_58'),
('Electronics - Screen Size', 'SCREEN_60'),
('Electronics - Screen Size', 'SCREEN_65'),
('Electronics - Screen Size', 'SCREEN_70'),
('Electronics - Screen Size', 'SCREEN_75'),
('Electronics - Screen Size', 'SCREEN_77'),
('Electronics - Screen Size', 'SCREEN_82'),
('Electronics - Screen Size', 'SCREEN_85'),
('Electronics - Screen Size', 'SCREEN_88'),
('Electronics - Screen Size', 'SCREEN_98'),

-- Storage Capacities
('Electronics - Storage', 'STORAGE_16GB'),
('Electronics - Storage', 'STORAGE_32GB'),
('Electronics - Storage', 'STORAGE_64GB'),
('Electronics - Storage', 'STORAGE_128GB'),
('Electronics - Storage', 'STORAGE_256GB'),
('Electronics - Storage', 'STORAGE_512GB'),
('Electronics - Storage', 'STORAGE_1TB'),
('Electronics - Storage', 'STORAGE_2TB'),
('Electronics - Storage', 'STORAGE_4TB'),
('Electronics - Storage', 'STORAGE_8TB'),
('Electronics - Storage', 'STORAGE_16TB'),
('Electronics - Storage', 'STORAGE_32TB'),
('Electronics - Storage', 'STORAGE_64TB'),

-- Memory/RAM Sizes
('Electronics - RAM', 'RAM_2GB'),
('Electronics - RAM', 'RAM_4GB'),
('Electronics - RAM', 'RAM_6GB'),
('Electronics - RAM', 'RAM_8GB'),
('Electronics - RAM', 'RAM_12GB'),
('Electronics - RAM', 'RAM_16GB'),
('Electronics - RAM', 'RAM_24GB'),
('Electronics - RAM', 'RAM_32GB'),
('Electronics - RAM', 'RAM_48GB'),
('Electronics - RAM', 'RAM_64GB'),
('Electronics - RAM', 'RAM_128GB'),
('Electronics - RAM', 'RAM_256GB'),
('Electronics - RAM', 'RAM_512GB'),
('Electronics - RAM', 'RAM_1TB'),

-- Mattress Sizes
('Mattress Sizes', 'MATTRESS_TWIN'),
('Mattress Sizes', 'MATTRESS_TWIN_XL'),
('Mattress Sizes', 'MATTRESS_FULL'),
('Mattress Sizes', 'MATTRESS_QUEEN'),
('Mattress Sizes', 'MATTRESS_KING'),
('Mattress Sizes', 'MATTRESS_CALIFORNIA_KING'),
('Mattress Sizes', 'MATTRESS_SPLIT_KING'),
('Mattress Sizes', 'MATTRESS_SPLIT_CALIFORNIA_KING'),

-- Tire Sizes (Common formats)
('Tire Sizes', 'TIRE_175_65R14'),
('Tire Sizes', 'TIRE_185_65R15'),
('Tire Sizes', 'TIRE_195_65R15'),
('Tire Sizes', 'TIRE_205_55R16'),
('Tire Sizes', 'TIRE_215_60R16'),
('Tire Sizes', 'TIRE_225_50R17'),
('Tire Sizes', 'TIRE_235_45R17'),
('Tire Sizes', 'TIRE_225_40R18'),
('Tire Sizes', 'TIRE_235_40R18'),
('Tire Sizes', 'TIRE_245_40R18'),
('Tire Sizes', 'TIRE_225_35R19'),
('Tire Sizes', 'TIRE_235_35R19'),
('Tire Sizes', 'TIRE_245_35R19'),
('Tire Sizes', 'TIRE_255_35R19'),
('Tire Sizes', 'TIRE_225_30R20'),
('Tire Sizes', 'TIRE_235_30R20'),
('Tire Sizes', 'TIRE_245_30R20'),
('Tire Sizes', 'TIRE_255_30R20'),
('Tire Sizes', 'TIRE_265_30R20'),
('Tire Sizes', 'TIRE_275_30R20'),
('Tire Sizes', 'TIRE_285_30R20'),
('Tire Sizes', 'TIRE_295_30R20'),
('Tire Sizes', 'TIRE_305_30R20'),

-- Generic Volume/Capacity
('Volume/Capacity', 'VOLUME_50ML'),
('Volume/Capacity', 'VOLUME_100ML'),
('Volume/Capacity', 'VOLUME_150ML'),
('Volume/Capacity', 'VOLUME_200ML'),
('Volume/Capacity', 'VOLUME_250ML'),
('Volume/Capacity', 'VOLUME_300ML'),
('Volume/Capacity', 'VOLUME_400ML'),
('Volume/Capacity', 'VOLUME_500ML'),
('Volume/Capacity', 'VOLUME_750ML'),
('Volume/Capacity', 'VOLUME_1L'),
('Volume/Capacity', 'VOLUME_1.5L'),
('Volume/Capacity', 'VOLUME_2L'),
('Volume/Capacity', 'VOLUME_3L'),
('Volume/Capacity', 'VOLUME_5L'),

-- Weight Categories
('Weight Categories', 'WEIGHT_1OZ'),
('Weight Categories', 'WEIGHT_2OZ'),
('Weight Categories', 'WEIGHT_4OZ'),
('Weight Categories', 'WEIGHT_8OZ'),
('Weight Categories', 'WEIGHT_1LB'),
('Weight Categories', 'WEIGHT_2LB'),
('Weight Categories', 'WEIGHT_5LB'),
('Weight Categories', 'WEIGHT_10LB'),
('Weight Categories', 'WEIGHT_25LB'),
('Weight Categories', 'WEIGHT_50LB'),
('Weight Categories', 'WEIGHT_100LB'),

-- Generic Size Categories
('Generic Size Categories', 'MINI'),
('Generic Size Categories', 'COMPACT'),
('Generic Size Categories', 'STANDARD'),
('Generic Size Categories', 'LARGE'),
('Generic Size Categories', 'EXTRA_LARGE'),
('Generic Size Categories', 'JUMBO'),
('Generic Size Categories', 'SUPER'),
('Generic Size Categories', 'MEGA'),
('Generic Size Categories', 'ULTRA'),
('Generic Size Categories', 'GIANT'),
('Generic Size Categories', 'FAMILY_SIZE'),
('Generic Size Categories', 'ECONOMY_SIZE'),
('Generic Size Categories', 'TRAVEL_SIZE'),
('Generic Size Categories', 'SAMPLE_SIZE'),
('Generic Size Categories', 'TRIAL_SIZE'),

-- Custom/Universal
('Custom/Universal', 'ONE_SIZE'),
('Custom/Universal', 'ONE_SIZE_FITS_ALL'),
('Custom/Universal', 'ADJUSTABLE'),
('Custom/Universal', 'CUSTOM'),
('Custom/Universal', 'MADE_TO_ORDER'),
('Custom/Universal', 'UNIVERSAL'),
('Custom/Universal', 'MULTI_SIZE'),
('Custom/Universal', 'ASSORTED');

CREATE INDEX idx_sizes_category ON Sizes(category);
CREATE INDEX idx_sizes_size_name ON Sizes(size_name);
CREATE INDEX idx_sizes_category_size ON Sizes(category, size_name);

CREATE TABLE IF NOT EXISTS Brands (
    brand_id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    brand_name VARCHAR(64)
);

ALTER TABLE Product
    ADD COLUMN size_id UUID;

ALTER TABLE Product
    ADD CONSTRAINT fk_size_id FOREIGN KEY (size_id) REFERENCES Sizes(size_id);

ALTER TABLE Product
    ADD COLUMN brand_id UUID;

ALTER TABLE Product
    ADD CONSTRAINT fk_brand_id FOREIGN KEY (brand_id) REFERENCES Brands(brand_id);


INSERT INTO Brands (brand_name) VALUES
-- Sports & Athletic Wear
('Nike'),
('Adidas'),
('Puma'),
('Reebok'),
('New Balance'),
('Under Armour'),
('Asics'),
('Converse'),
('Vans'),
('Fila'),
('Champion'),
('Lacoste'),
('Skechers'),
('Hoka'),
('Brooks'),
('Saucony'),
('Jordan'),
('Columbia'),
('The North Face'),
('Timberland'),
('Crocs'),
('Salomon'),
('Merrell'),
('Patagonia'),
('Arc''teryx'),
('Mammut'),
('Haglöfs'),
('Outdoor Research'),
('Black Diamond'),
('Osprey'),
('Deuter'),
('Gregory'),
('Thule'),
('Dakine'),
('Burton'),
('Volcom'),
('Quicksilver'),
('Roxy'),
('Billabong'),
('O''Neill'),
('Hurley'),
('Rip Curl'),
('Oakley'),
('Ray-Ban'),
('Speedo'),
('Arena'),
('TYR'),
('Mizuno'),
('Yonex'),
('Head'),
('Wilson'),
('Babolat'),
('Prince'),
('Dunlop'),
('Spalding'),
('Rawlings'),
('Louisville Slugger'),
('Easton'),
('DeMarini'),
('Marucci'),
('Victus'),

-- Luxury Fashion
('Gucci'),
('Prada'),
('Louis Vuitton'),
('Hermès'),
('Chanel'),
('Dior'),
('Versace'),
('Burberry'),
('Balenciaga'),
('Saint Laurent'),
('Bottega Veneta'),
('Fendi'),
('Celine'),
('Givenchy'),
('Valentino'),
('Tom Ford'),
('Alexander McQueen'),
('Stella McCartney'),
('Moschino'),
('Dolce & Gabbana'),
('Armani'),
('Emporio Armani'),
('Giorgio Armani'),
('Brunello Cucinelli'),
('Loro Piana'),
('Ermenegildo Zegna'),
('Canali'),
('Brioni'),
('Kiton'),
('Isaia'),
('Berluti'),
('Goyard'),
('Moynat'),
('Delvaux'),
('Strathberry'),
('Mansur Gavriel'),
('Staud'),
('Jacquemus'),
('Ganni'),
('Acne Studios'),
('Maison Margiela'),
('Comme des Garçons'),
('Yohji Yamamoto'),
('Issey Miyake'),
('Kenzo'),
('Opening Ceremony'),
('Proenza Schouler'),
('The Row'),
('Totême'),
('Lemaire'),
('JW Anderson'),
('Wales Bonner'),
('Martine Rose'),
('Stone Island'),
('C.P. Company'),
('Moncler'),
('Canada Goose'),
('Woolrich'),
('Barbour'),
('Mackage'),
('Nobis'),

-- Mass Market Fashion
('Zara'),
('H&M'),
('Uniqlo'),
('Forever 21'),
('Primark'),
('Topshop'),
('ASOS'),
('Boohoo'),
('Shein'),
('Romwe'),
('Zaful'),
('Fashion Nova'),
('PrettyLittleThing'),
('Missguided'),
('Urban Outfitters'),
('American Eagle'),
('Abercrombie & Fitch'),
('Hollister'),
('PacSun'),
('Brandy Melville'),
('Free People'),
('Anthropologie'),
('J.Crew'),
('Banana Republic'),
('Gap'),
('Old Navy'),
('Target'),
('Walmart'),
('Costco'),
('Kohl''s'),
('JCPenney'),
('Macy''s'),
('Nordstrom'),
('Bloomingdale''s'),
('Saks Fifth Avenue'),
('Neiman Marcus'),
('Bergdorf Goodman'),
('Barneys'),
('Net-a-Porter'),
('Mr Porter'),
('Farfetch'),
('Mytheresa'),
('24S'),
('MatchesFashion'),
('SSENSE'),
('Forward'),
('Revolve'),
('Shopbop'),

-- Denim & Casual Wear
('Levi''s'),
('Wrangler'),
('Lee'),
('Diesel'),
('G-Star RAW'),
('True Religion'),
('7 For All Mankind'),
('Citizens of Humanity'),
('AG Jeans'),
('Frame'),
('Mother'),
('Paige'),
('J Brand'),
('Hudson'),
('Rock Revival'),
('Miss Me'),
('Buckle'),
('American Eagle Outfitters'),
('Hollister'),
('Abercrombie'),
('Guess'),
('Tommy Hilfiger'),
('Ralph Lauren'),
('Polo Ralph Lauren'),
('Calvin Klein'),
('DKNY'),
('Michael Kors'),
('Kate Spade'),
('Coach'),
('Tory Burch'),
('Marc Jacobs'),
('Rebecca Minkoff'),
('Furla'),
('Longchamp'),
('Kipling'),

-- Streetwear & Contemporary
('Supreme'),
('Off-White'),
('Fear of God'),
('Essentials'),
('Stussy'),
('BAPE'),
('Kith'),
('Palace'),
('Anti Social Social Club'),
('Golf Wang'),
('Tyler, The Creator'),
('Pharrell Williams'),
('Human Made'),
('Neighborhood'),
('Undercover'),
('Visvim'),
('White Mountaineering'),
('Sacai'),
('Fragment'),
('Mastermind'),
('Rick Owens'),
('Raf Simons'),
('Helmut Lang'),
('Haider Ackermann'),
('Dries Van Noten'),
('Ann Demeulemeester'),
('Boris Bidjan Saberi'),
('Julius'),
('11 by Boris Bidjan Saberi'),
('Y-3'),
('Adidas Originals'),
('Nike SB'),
('Vans Off The Wall'),
('Thrasher'),
('Independent'),
('Spitfire'),
('Santa Cruz'),
('Powell Peralta'),
('Bones'),
('Element'),
('Plan B'),
('Girl'),
('Chocolate'),
('Primitive'),
('Diamond Supply Co.'),
('HUF'),
('Obey'),
('The Hundreds'),
('Rebel8'),
('Mishka'),
('Crooks & Castles'),

-- Electronics & Technology
('Apple'),
('Samsung'),
('Google'),
('Microsoft'),
('Sony'),
('LG'),
('Panasonic'),
('Philips'),
('Sharp'),
('Toshiba'),
('Hitachi'),
('JVC'),
('Pioneer'),
('Yamaha'),
('Denon'),
('Marantz'),
('Onkyo'),
('Harman Kardon'),
('JBL'),
('Bose'),
('Beats'),
('Sennheiser'),
('Audio-Technica'),
('Shure'),
('AKG'),
('Beyerdynamic'),
('Focal'),
('KEF'),
('B&W'),
('Klipsch'),
('Polk Audio'),
('Definitive Technology'),
('Sonos'),
('Bang & Olufsen'),
('Devialet'),
('McIntosh'),
('Mark Levinson'),
('Krell'),
('Wilson Audio'),
('Magico'),
('YG Acoustics'),
('Rockport Technologies'),

-- Computing & Mobile
('Dell'),
('HP'),
('Lenovo'),
('Asus'),
('Acer'),
('MSI'),
('Alienware'),
('Razer'),
('Corsair'),
('Logitech'),
('SteelSeries'),
('HyperX'),
('Cooler Master'),
('Thermaltake'),
('NZXT'),
('Fractal Design'),
('be quiet!'),
('Seasonic'),
('EVGA'),
('NVIDIA'),
('AMD'),
('Intel'),
('Qualcomm'),
('MediaTek'),
('Broadcom'),
('Realtek'),
('Western Digital'),
('Seagate'),
('Crucial'),
('Kingston'),
('G.Skill'),
('Corsair Memory'),
('Samsung Memory'),
('SK Hynix'),
('Micron'),
('SanDisk'),
('Lexar'),
('PNY'),
('ADATA'),
('Transcend'),
('Patriot'),
('Team Group'),
('GeIL'),
('Mushkin'),

-- Mobile Devices
('iPhone'),
('iPad'),
('Galaxy'),
('Pixel'),
('OnePlus'),
('Xiaomi'),
('Huawei'),
('Oppo'),
('Vivo'),
('Realme'),
('Honor'),
('Motorola'),
('Nokia'),
('BlackBerry'),
('HTC'),
('Zte'),
('TCL'),
('Alcatel'),
('Meizu'),
('LeEco'),
('Asus ROG Phone'),
('Red Magic'),
('Black Shark'),
('Legion Phone'),
('iPhone Pro'),
('Galaxy Note'),
('Galaxy Fold'),
('Galaxy Flip'),
('Pixel Pro'),
('Pixel Fold'),

-- Gaming
('PlayStation'),
('Xbox'),
('Nintendo'),
('Steam'),
('Epic Games'),
('Valve'),
('Blizzard'),
('Activision'),
('Electronic Arts'),
('EA Sports'),
('Ubisoft'),
('Take-Two'),
('Rockstar Games'),
('CD Projekt'),
('Square Enix'),
('Capcom'),
('Konami'),
('Bandai Namco'),
('Sega'),
('Atlus'),
('From Software'),
('Kojima Productions'),
('Naughty Dog'),
('Santa Monica Studio'),
('Insomniac Games'),
('Sucker Punch'),
('Guerrilla Games'),
('343 Industries'),
('Turn 10 Studios'),
('Playground Games'),
('The Coalition'),
('Rare'),
('Mojang'),
('Game Freak'),
('HAL Laboratory'),
('Intelligent Systems'),
('Next Level Games'),
('PlatinumGames'),
('Arc System Works'),
('SNK'),
('King of Fighters'),
('Tekken'),
('Street Fighter'),
('Mortal Kombat'),
('Super Smash Bros'),
('Call of Duty'),
('Battlefield'),
('Apex Legends'),
('Fortnite'),
('PUBG'),
('Valorant'),
('Counter-Strike'),
('Overwatch'),
('League of Legends'),
('Dota'),
('World of Warcraft'),
('Final Fantasy'),
('The Elder Scrolls'),
('Fallout'),
('Grand Theft Auto'),
('Red Dead Redemption'),
('The Witcher'),
('Cyberpunk'),
('Assassin''s Creed'),
('Far Cry'),
('Watch Dogs'),
('Splinter Cell'),
('Rainbow Six'),
('Ghost Recon'),
('The Division'),
('Halo'),
('Gears of War'),
('Forza'),
('Fable'),
('State of Decay'),
('Sea of Thieves'),
('The Legend of Zelda'),
('Super Mario'),
('Metroid'),
('Pokémon'),
('Fire Emblem'),
('Xenoblade'),
('Bayonetta'),
('Splatoon'),
('Animal Crossing'),
('Mario Kart'),
('Super Smash Bros'),
('Donkey Kong'),
('Kirby'),
('Star Fox'),
('F-Zero'),


-- Home Appliances
('Whirlpool'),
('GE'),
('Frigidaire'),
('KitchenAid'),
('Maytag'),
('Bosch'),
('Miele'),
('Siemens'),
('Electrolux'),
('AEG'),
('Zanussi'),
('Indesit'),
('Hotpoint'),
('Beko'),
('Grundig'),
('Arçelik'),
('Haier'),
('Midea'),
('Gree'),
('Hisense'),
('TCL'),
('Changhong'),
('Konka'),
('Skyworth'),
('Amana'),
('Kenmore'),
('Fisher & Paykel'),
('Smeg'),
('Bertazzoni'),
('La Cornue'),
('Viking'),
('Wolf'),
('Sub-Zero'),
('Thermador'),
('Gaggenau'),
('Liebherr'),
('Asko'),
('Speed Queen'),
('Wascomat'),
('Huebsch'),
('Primus'),
('Crossover'),
('Milnor'),
('Pellerin'),
('Jensen'),
('Alliance'),
('Quantum'),
('Unimac'),
('UC'),
('American Dryer'),
('World Dryer'),
('Excel'),
('Saniflow'),
('Bradley'),
('Bobrick'),
('Kimberly-Clark'),
('Tork'),
('Georgia-Pacific'),
('Cascades'),
('Kruger'),
('Irving'),
('Resolute'),
('Domtar'),
('International Paper'),
('WestRock'),
('Packaging Corporation'),
('Sonoco'),
('Crown Holdings'),
('Ball Corporation'),
('Silgan'),
('CCL Industries'),
('Multi-Color'),
('Avery Dennison'),
('3M'),
('Scotch'),
('Post-it'),
('Command'),
('Scotch-Brite'),
('Filtrete'),
('Nexcare'),
('Tegaderm'),
('Coban'),
('Micropore'),
('Transpore'),
('Durapore'),
('Blenderm'),
('Medipore'),
('Steri-Strip'),
('Tegasorb'),
('Tegaderm'),
('Opsite'),
('Bioclusive'),
('Hydrofera'),
('Aquacel'),
('Kaltostat'),
('Seasorb'),
('Maxorb'),
('Biatain'),
('Mepilex'),
('Safetac'),
('Mepitel'),
('Mepiform'),
('Mepitac'),
('Mefix'),
('Hypafix'),
('Fixomull'),
('Leukoplast'),
('Leukopor'),
('Leukomed'),
('Cutiplast'),
('Cosmopor'),
('Cosmopore'),
('Primapore'),
('Optifix'),
('Optipore'),
('Airstrip'),
('Duoderm'),
('Granuflex'),
('Comfeel'),
('Triad'),
('Intrasite'),
('Purilon'),
('Normlgel'),
('Askina'),
('UrgoClean'),
('UrgoStart'),
('Urgotul'),
('UrgoK2'),
('Jobst'),
('Juzo'),
('Sigvaris'),
('Medi'),
('Bauerfeind'),
('Thuasne'),
('Orliman'),
('Ottobock'),
('Össur'),
('Hanger'),
('Fillauer'),
('WillowWood'),
('Ohio Willow Wood'),
('Endolite'),
('Blatchford'),
('Steeper'),
('RSLSteeper'),
('Touch Bionics'),
('i-limb'),
('bebionic'),
('Michelangelo'),
('SensorHand'),
('Vincent'),
('AxonHook'),
('AxonRotate'),
('DynamicArm'),
('ErgoArm'),
('EnergyArm'),
('VariPlus'),
('Harmony'),
('Unity'),
('AquaLimb'),
('Aqua-Liner'),
('Alpha'),
('Shuttle'),
('SmartTemp'),
('SmartSock'),
('WaveGel'),
('SoftSilicone'),
('ActiveSkin'),
('NaturalFeel'),
('ComfortFlex'),
('DuraFlex'),
('UltraFlex'),
('MaxFlex'),
('ProFlex'),
('FlexiFit'),
('EasyFit'),
('CustomFit'),
('PerfectFit'),
('TrueFit'),
('SecureFit'),
('ComfortGrip');