
CREATE TYPE STATUS_NEW AS ENUM ('PENDING', 'DELIVERED', 'CANCELLED');

ALTER TABLE Orders ALTER COLUMN status DROP DEFAULT;

ALTER TABLE Orders ALTER COLUMN status TYPE STATUS_NEW USING status::text::STATUS_NEW;

ALTER TABLE Orders ALTER COLUMN status SET DEFAULT 'PENDING';

DROP TYPE STATUS;

ALTER TYPE STATUS_NEW RENAME TO STATUS;